# Generated by Django 5.1.7 on 2025-03-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_logisticpartner'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='logistic_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logistic_partner', to='auth_app.logisticpartner'),
        ),
    ]
