# Generated by Django 5.1.7 on 2025-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_deliveryrequest_logistic_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
    ]
