# Generated by Django 5.1.7 on 2025-03-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
        ('auth_app', '0005_remove_organization_phone_donor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_organization', to='auth_app.organization'),
        ),
    ]
