# Generated by Django 5.1.7 on 2025-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_alter_requestresource_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresource',
            name='pic',
            field=models.ImageField(blank=True, upload_to='organization/'),
        ),
    ]
