# Generated by Django 5.1.7 on 2025-03-30 03:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_requestresource_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
