# Generated by Django 5.1.7 on 2025-03-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0005_requestresource_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresource',
            name='pick_up_available',
            field=models.BooleanField(default=False),
        ),
    ]
