# Generated by Django 5.1.7 on 2025-03-31 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_requestresource_pick_up_available'),
        ('auth_app', '0006_logisticpartner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestresource',
            old_name='pick_up_available',
            new_name='is_donated',
        ),
        migrations.AddField(
            model_name='requestresource',
            name='logistic_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistic_partner_organization', to='auth_app.logisticpartner'),
        ),
    ]
