# Generated by Django 5.1.7 on 2025-03-31 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0007_rename_pick_up_available_requestresource_is_donated_and_more'),
        ('auth_app', '0007_organization_logisticpartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestresource',
            name='is_donated',
        ),
        migrations.AddField(
            model_name='requestresource',
            name='donated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donated_by_donor', to='auth_app.donor'),
        ),
    ]
