# Generated by Django 5.1.7 on 2025-03-28 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('license', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
