# Generated by Django 5.1.7 on 2025-03-30 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_organization_phone_donor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticPartner',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('license', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('noe', models.IntegerField(default=1)),
                ('available_employee', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logistic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
