# Generated by Django 5.1.7 on 2025-03-31 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_logisticpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logisticPartner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_logistic_partner', to='auth_app.logisticpartner'),
        ),
    ]
