# Generated by Django 5.1.7 on 2025-03-31 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableDays',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='available_days',
        ),
    ]
