# Generated by Django 5.1.7 on 2025-03-31 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_requestresource_pick_up_available'),
        ('donations', '0002_delete_availabledays_delete_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='donated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donated_to_request', to='Organization.requestresource'),
        ),
    ]
