# Generated by Django 5.1.7 on 2025-03-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donations_donated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
